import type { Region } from "@/constants/region/region";

export const PREFECTURES = [
  "HOKKAIDO",
  "AOMORI",
  "IWATE",
  "MIYAGI",
  "AKITA",
  "YAMAGATA",
  "FUKUSHIMA",
  "IBARAKI",
  "TOCHIGI",
  "GUNMA",
  "SAITAMA",
  "CHIBA",
  "TOKYO",
  "KANAGAWA",
  "NIIGATA",
  "TOYAMA",
  "ISHIKAWA",
  "FUKUI",
  "YAMANASHI",
  "NAGANO",
  "GIFU",
  "SHIZUOKA",
  "AICHI",
  "MIE",
  "SHIGA",
  "KYOTO",
  "OSAKA",
  "HYOGO",
  "NARA",
  "WAKAYAMA",
  "TOTTORI",
  "SHIMANE",
  "OKAYAMA",
  "HIROSHIMA",
  "YAMAGUCHI",
  "TOKUSHIMA",
  "KAGAWA",
  "EHIME",
  "KOCHI",
  "FUKUOKA",
  "SAGA",
  "NAGASAKI",
  "KUMAMOTO",
  "OITA",
  "MIYAZAKI",
  "KAGOSHIMA",
  "OKINAWA",
] as const;

export type Prefecture = (typeof PREFECTURES)[number];

/** 都道府県 → 地方区分。表示名は messages 側で持つ。 */
export const PREFECTURE_REGION: Record<Prefecture, Region> = {
  HOKKAIDO: "HOKKAIDO",
  AOMORI: "TOHOKU",
  IWATE: "TOHOKU",
  MIYAGI: "TOHOKU",
  AKITA: "TOHOKU",
  YAMAGATA: "TOHOKU",
  FUKUSHIMA: "TOHOKU",
  IBARAKI: "KANTO",
  TOCHIGI: "KANTO",
  GUNMA: "KANTO",
  SAITAMA: "KANTO",
  CHIBA: "KANTO",
  TOKYO: "KANTO",
  KANAGAWA: "KANTO",
  NIIGATA: "CHUBU",
  TOYAMA: "CHUBU",
  ISHIKAWA: "CHUBU",
  FUKUI: "CHUBU",
  YAMANASHI: "CHUBU",
  NAGANO: "CHUBU",
  GIFU: "CHUBU",
  SHIZUOKA: "CHUBU",
  AICHI: "CHUBU",
  MIE: "KANSAI",
  SHIGA: "KANSAI",
  KYOTO: "KANSAI",
  OSAKA: "KANSAI",
  HYOGO: "KANSAI",
  NARA: "KANSAI",
  WAKAYAMA: "KANSAI",
  TOTTORI: "CHUGOKU",
  SHIMANE: "CHUGOKU",
  OKAYAMA: "CHUGOKU",
  HIROSHIMA: "CHUGOKU",
  YAMAGUCHI: "CHUGOKU",
  TOKUSHIMA: "SHIKOKU",
  KAGAWA: "SHIKOKU",
  EHIME: "SHIKOKU",
  KOCHI: "SHIKOKU",
  FUKUOKA: "KYUSHU",
  SAGA: "KYUSHU",
  NAGASAKI: "KYUSHU",
  KUMAMOTO: "KYUSHU",
  OITA: "KYUSHU",
  MIYAZAKI: "KYUSHU",
  KAGOSHIMA: "KYUSHU",
  OKINAWA: "OKINAWA",
};

export const toRegion = (prefecture: Prefecture): Region =>
  PREFECTURE_REGION[prefecture];
