import type { Region } from "@/constants/region/region";

export const PREFECTURES = [
  "HOKKAIDO",
  "AOMORI",
  "IWATE",
  "MIYAGI",
  "AKITA",
  "YAMAGATA",
  "FUKUSHIMA",
  "IBARAKI",
  "TOCHIGI",
  "GUNMA",
  "SAITAMA",
  "CHIBA",
  "TOKYO",
  "KANAGAWA",
  "NIIGATA",
  "TOYAMA",
  "ISHIKAWA",
  "FUKUI",
  "YAMANASHI",
  "NAGANO",
  "GIFU",
  "SHIZUOKA",
  "AICHI",
  "MIE",
  "SHIGA",
  "KYOTO",
  "OSAKA",
  "HYOGO",
  "NARA",
  "WAKAYAMA",
  "TOTTORI",
  "SHIMANE",
  "OKAYAMA",
  "HIROSHIMA",
  "YAMAGUCHI",
  "TOKUSHIMA",
  "KAGAWA",
  "EHIME",
  "KOCHI",
  "FUKUOKA",
  "SAGA",
  "NAGASAKI",
  "KUMAMOTO",
  "OITA",
  "MIYAZAKI",
  "KAGOSHIMA",
  "OKINAWA",
] as const;

export type Prefecture = (typeof PREFECTURES)[number];

interface PrefectureDefinition {
  label: string;
  region: Region;
}

/** 都道府県カタログ。表示名と地方区分だけを持つデータ表（クラス化しない）。 */
export const PREFECTURE_CATALOG: Record<Prefecture, PrefectureDefinition> = {
  HOKKAIDO: { label: "北海道", region: "HOKKAIDO" },
  AOMORI: { label: "青森県", region: "TOHOKU" },
  IWATE: { label: "岩手県", region: "TOHOKU" },
  MIYAGI: { label: "宮城県", region: "TOHOKU" },
  AKITA: { label: "秋田県", region: "TOHOKU" },
  YAMAGATA: { label: "山形県", region: "TOHOKU" },
  FUKUSHIMA: { label: "福島県", region: "TOHOKU" },
  IBARAKI: { label: "茨城県", region: "KANTO" },
  TOCHIGI: { label: "栃木県", region: "KANTO" },
  GUNMA: { label: "群馬県", region: "KANTO" },
  SAITAMA: { label: "埼玉県", region: "KANTO" },
  CHIBA: { label: "千葉県", region: "KANTO" },
  TOKYO: { label: "東京都", region: "KANTO" },
  KANAGAWA: { label: "神奈川県", region: "KANTO" },
  NIIGATA: { label: "新潟県", region: "CHUBU" },
  TOYAMA: { label: "富山県", region: "CHUBU" },
  ISHIKAWA: { label: "石川県", region: "CHUBU" },
  FUKUI: { label: "福井県", region: "CHUBU" },
  YAMANASHI: { label: "山梨県", region: "CHUBU" },
  NAGANO: { label: "長野県", region: "CHUBU" },
  GIFU: { label: "岐阜県", region: "CHUBU" },
  SHIZUOKA: { label: "静岡県", region: "CHUBU" },
  AICHI: { label: "愛知県", region: "CHUBU" },
  MIE: { label: "三重県", region: "KANSAI" },
  SHIGA: { label: "滋賀県", region: "KANSAI" },
  KYOTO: { label: "京都府", region: "KANSAI" },
  OSAKA: { label: "大阪府", region: "KANSAI" },
  HYOGO: { label: "兵庫県", region: "KANSAI" },
  NARA: { label: "奈良県", region: "KANSAI" },
  WAKAYAMA: { label: "和歌山県", region: "KANSAI" },
  TOTTORI: { label: "鳥取県", region: "CHUGOKU" },
  SHIMANE: { label: "島根県", region: "CHUGOKU" },
  OKAYAMA: { label: "岡山県", region: "CHUGOKU" },
  HIROSHIMA: { label: "広島県", region: "CHUGOKU" },
  YAMAGUCHI: { label: "山口県", region: "CHUGOKU" },
  TOKUSHIMA: { label: "徳島県", region: "SHIKOKU" },
  KAGAWA: { label: "香川県", region: "SHIKOKU" },
  EHIME: { label: "愛媛県", region: "SHIKOKU" },
  KOCHI: { label: "高知県", region: "SHIKOKU" },
  FUKUOKA: { label: "福岡県", region: "KYUSHU" },
  SAGA: { label: "佐賀県", region: "KYUSHU" },
  NAGASAKI: { label: "長崎県", region: "KYUSHU" },
  KUMAMOTO: { label: "熊本県", region: "KYUSHU" },
  OITA: { label: "大分県", region: "KYUSHU" },
  MIYAZAKI: { label: "宮崎県", region: "KYUSHU" },
  KAGOSHIMA: { label: "鹿児島県", region: "KYUSHU" },
  OKINAWA: { label: "沖縄県", region: "OKINAWA" },
};

export const toRegion = (prefecture: Prefecture): Region =>
  PREFECTURE_CATALOG[prefecture].region;

export const prefectureLabel = (prefecture: Prefecture): string =>
  PREFECTURE_CATALOG[prefecture].label;
